plainternet_user:
    resource: "@PlainternetUserBundle/Resources/config/routing.yml"
    prefix:   /

plainternet_file_manager:
    resource: "@PlainternetFileManagerBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
